/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.Laporan;
import model.Petani;
import model.Petugas;
import model.hasilTani;
import model.tbl_AkunPetani;
import model.tbl_AkunPetugas;
import model.tbl_DHasilTani;
import model.tbl_HasilTani;
import model.tbl_Laporan;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
/**x    
 *
 * @author AsemJr
 */
public class aplikasiStatistikTaniAdmin extends javax.swing.JFrame {

    /**
     * Creates new form sistemStatistikTaniDriver
     */
    private Connection koneksi;
    private Statement script;
    private tbl_AkunPetani DataKontakPetani;
    private tbl_AkunPetugas DataKontakPetugas;
    private tbl_Laporan DataKontakLaporan;
    private tbl_HasilTani DataKontakHTBalige;
    private tbl_HasilTani DataKontakHTPorsea;
    private tbl_HasilTani DataKontakHTSigumpar;
    private tbl_HasilTani DataKontakHTSiantarN;
    private tbl_HasilTani DataKontakHTLaguboti;
    private tbl_DHasilTani DataKontakDHT;
    public aplikasiStatistikTaniAdmin() {
        initComponents();
        
        DataKontakPetani = new tbl_AkunPetani();
        tbl_DAPetani.setModel(DataKontakPetani);
        
        DataKontakPetugas = new tbl_AkunPetugas();
        tbl_DAPetugas.setModel(DataKontakPetugas);
        
        DataKontakLaporan = new tbl_Laporan();
        tbl_Laporan.setModel(DataKontakLaporan);
        DataKontakDHT = new tbl_DHasilTani();
        tblDHT.setModel(DataKontakDHT);
        
        DataKontakHTBalige = new tbl_HasilTani();
        tblBalige.setModel(DataKontakHTBalige);
        
        DataKontakHTSigumpar = new tbl_HasilTani();
        tblSigumpar.setModel(DataKontakHTSigumpar);
        
    
        DataKontakHTLaguboti = new tbl_HasilTani();
        tblLaguboti.setModel(DataKontakHTLaguboti);
        
        DataKontakHTPorsea = new tbl_HasilTani();
        tblPorsea.setModel(DataKontakHTBalige);
        
        
        
        
        
             KoneksiDb();
             tampilPetani();
             tampilPetugas();
             tampilLaporan();
             tampilBalige();
           tampilSigumpar();
             tampilLaguboti();
//             tampilPorsea();
             tampilDHT();
             //clear();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDHT = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBalige = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPorsea = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSigumpar = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblLaguboti = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Laporan = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FPAnama = new javax.swing.JTextField();
        FPAalamat = new javax.swing.JTextField();
        FPAusername = new javax.swing.JTextField();
        FPAnomorTelephone = new javax.swing.JTextField();
        FPApassword = new javax.swing.JTextField();
        FPAtambahAkun = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        FPApetugas = new javax.swing.JRadioButton();
        FPApetani = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FEAusernameLama = new javax.swing.JTextField();
        FEApasswordLama = new javax.swing.JTextField();
        FEAusernameBaru = new javax.swing.JTextField();
        FEApasswordBaru = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        FEApetugas = new javax.swing.JRadioButton();
        FEApetani = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DAPetani = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DAPetugas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame3.setVisible(true);

        tblDHT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kecamatan", "Jenis Hasil Tani", "Bulan", "Jumlah"
            }
        ));
        jScrollPane6.setViewportView(tblDHT);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Tabel Data Hasil Tani");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );

        jTabbedPane2.addTab("Data Hasil Tani", jPanel2);

        jButton4.setText("Chart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton4)
                .addContainerGap(620, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addContainerGap(617, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Total Statistik Pertanian", jPanel5);

        tblBalige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Padi", null, null},
                {"Jagung", null, null},
                {"Cabai", null, null},
                {"Kentang", null, null},
                {null, null, null}
            },
            new String [] {
                "Jenis hasil Tani", "Bulan", "Jumlah"
            }
        ));
        jScrollPane4.setViewportView(tblBalige);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Balige");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Porsea");

        tblPorsea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jenis Hasil Tani", "Bulan", "Jumlah"
            }
        ));
        jScrollPane5.setViewportView(tblPorsea);

        jLabel23.setText("Laguboti");

        jLabel24.setText("Sigumpar");

        tblSigumpar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jenis Hasil Tani", "Bulan", "Jumlah"
            }
        ));
        jScrollPane8.setViewportView(tblSigumpar);

        tblLaguboti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jenis Hasil Tani", "Bulan", "Jumlah"
            }
        ));
        jScrollPane9.setViewportView(tblLaguboti);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(0, 650, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        jTabbedPane3.addTab("Statistik Berdasarkan Kecamatan", jPanel6);

        jTabbedPane2.addTab("Data Statistik Pertanian", jTabbedPane3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Laporan Pertanian Bulan Juni");

        tbl_Laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Pengirim", "Tanggal", "Subjek", "Laporan Pengamatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_Laporan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );

        jTabbedPane2.addTab("Data Laporan", jPanel4);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Form Penambahan Akun");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Username            :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password             :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama                    :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Alamat                  :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nomor Telephone :");

        FPAusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPAusernameActionPerformed(evt);
            }
        });

        FPAtambahAkun.setText("Tambah");
        FPAtambahAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPAtambahAkunActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Posisi Sebagai        :");

        FPApetugas.setText("Petugas");

        FPApetani.setText("Petani");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("*Posisi Wajib Diisi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(FPApassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(FPAnama, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(FPAalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FPAusername, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FPAnomorTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(FPAtambahAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(FPApetugas)
                        .addGap(18, 18, 18)
                        .addComponent(FPApetani))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FPAnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(FPAalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FPAnomorTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FPAusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FPApassword))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(FPApetugas)
                    .addComponent(FPApetani))
                .addGap(19, 19, 19)
                .addComponent(FPAtambahAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("Form Penambahan Akun", jPanel7);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Username          :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Password           :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Password Baru    :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Form Edit Akun");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Username Baru   :");

        FEAusernameBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEAusernameBaruActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setText("Untuk Delete, Isi Text Field username saja");

        FEApetugas.setText("Petugas");

        FEApetani.setText("Petani");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FEApasswordLama))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FEAusernameLama, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FEApasswordBaru))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FEAusernameBaru)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton1)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FEApetugas)
                                .addGap(39, 39, 39)))
                        .addComponent(FEApetani)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(FEAusernameLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(FEApasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(FEAusernameBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(FEApasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FEApetugas)
                    .addComponent(FEApetani))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Form Edit Akun", jPanel1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Data Akun Petani");

        tbl_DAPetani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Nomor Telephone", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_DAPetani);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 570, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Data Akun Petani", jPanel8);

        tbl_DAPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Nomor Telephone", "Username", "Password"
            }
        ));
        jScrollPane2.setViewportView(tbl_DAPetugas);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Data Akun Petugas");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Akun Petugas", jPanel9);

        jTabbedPane2.addTab("Pengaturan Akun", jTabbedPane1);

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(2, 2, 2))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel25))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new formLogin().show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FPAtambahAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPAtambahAkunActionPerformed

        if(FPApetani.isSelected()){
            tambahPetani();}
        else if(FPApetugas.isSelected()){
            tambahPetugas(); }
        else{
            JOptionPane.showMessageDialog(this, "Pilih Posisi Sebagai");
        }
    }//GEN-LAST:event_FPAtambahAkunActionPerformed

    private void FPAusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPAusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FPAusernameActionPerformed

    private void FEAusernameBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEAusernameBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEAusernameBaruActionPerformed
public void gantiAkun(){
    
        try{
            if(FEApetugas.isSelected()){
        String sql="UPDATE `akunpetugas` SET `username`='"+FEAusernameBaru.getText()+"',`password`='"+FEApasswordBaru.getText()+"' WHERE username='"+FEAusernameLama.getText()+"' "  ;  
         script.executeUpdate(sql);
         JOptionPane.showMessageDialog(null, FEAusernameLama.getText()+" berhasil Diupdate Menjadi"+FEAusernameBaru.getText());
            }
            else if(FEApetani.isSelected()){
              String sql="UPDATE `akunpetani` SET `username`='"+FEAusernameBaru.getText()+"',`password`='"+FEApasswordBaru.getText()+"' WHERE username='"+FEAusernameLama.getText()+"' "  ;  
            script.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, FEAusernameLama.getText()+" berhasil Diupdate Menjadi"+FEAusernameBaru.getText());
            }



JOptionPane.showMessageDialog(null, FEAusernameLama.getText()+" berhasil Diupdate Menjadi"+FEAusernameBaru.getText());
//clear();
}
catch(SQLException ex){
JOptionPane.showMessageDialog(this, "SQL nya salah");
//clear();
}

}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
gantiAkun();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void hapusAkun(){
    
        try{
            if(FEApetugas.isSelected()){
        String sql="DELETE From `akunpetugas` WHERE username='"+FEAusernameLama.getText()+"' "  ;  
         script.executeUpdate(sql);
         JOptionPane.showMessageDialog(null, FEAusernameLama.getText()+" berhasil Diupdate Menjadi "+FEAusernameBaru.getText());
            tampilPetani();
            }
            else if(FEApetani.isSelected()){
        String sql="DELETE From `akunpetani` WHERE username='"+FEAusernameLama.getText()+"' "  ;  
            script.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, FEAusernameLama.getText()+" berhasil Diupdate Menjadi "+FEAusernameBaru.getText());
            tampilPetugas();
            }




}
catch(SQLException ex){
JOptionPane.showMessageDialog(this, "SQL nya salah");
//clear();
}

}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
hapusAkun();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/pbomenujua",
                    "root",
                    ""
            );
            
            Statement statement = connect.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from datahasiltani ");
            DefaultPieDataset dataset = new DefaultPieDataset();
            while (resultSet.next()){
                dataset.setValue(
                        resultSet.getString("Kecamatan"),
                        Double.parseDouble(resultSet.getString("Jumlah"))
                        );
            }
            
            JFreeChart chart = ChartFactory.createPieChart("Chart Statistik Pertanian Tobasa", dataset, true, true, false);
            ChartFrame frame = new ChartFrame("Chart Statistika Pertanian Tobasa",chart);
            frame.setVisible(true);
            frame.setSize(500, 500);
           
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
public void tambahPetani(){
    
        try{
        String sql = "INSERT INTO `akunpetani` (`Nama`, `Alamat`, `noTelephone`, `username`, `password`) VALUES ('"+FPAnama.getText()+"','"+FPAalamat.getText()+"',"
                + "'"+FPAnomorTelephone.getText()+"','"+FPAusername.getText()+"','"+FPApassword.getText()+"'); " ;

script.executeUpdate(sql);

tampilPetani();
JOptionPane.showMessageDialog(null, FPAnama.getText()+" berhasil Disimpan");
//clear();
}
catch(SQLException ex){
JOptionPane.showMessageDialog(this, "SQLnya Salah ");
//clear();
}

}

public void tambahPetugas(){
    
        try{
        String sql = "INSERT INTO `akunpetugas` (`Nama`, `Alamat`, `noTelephone`, `username`, `password`) VALUES ('"+FPAnama.getText()+"','"+FPAalamat.getText()+"',"
                + "'"+FPAnomorTelephone.getText()+"','"+FPAusername.getText()+"','"+FPApassword.getText()+"'); " ;
//                "insert into akunpetugas(`Nama`, `Alamat`, `noTelephone`, `username`, `password`)"
//                + " values ("
//            +"'"+FPAnama.getText()+"',"
//            +"'"+FPAalamat.getText()+"',"
//            +"'"+FPAnomorTelephone.getText()+"',"
//            +"'"+FPAusername.getText()+"',"
//            +"'"+FPApassword.getText()+"',"
//                
//            +")";

script.executeUpdate(sql);

tampilPetugas();
JOptionPane.showMessageDialog(null, FPAnama.getText()+" berhasil Disimpan");
//clear();
}
catch(SQLException ex){
JOptionPane.showMessageDialog(this, "SQL nya salah");
//clear();
}

}
private void KoneksiDb( ){ 
        try{
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbomenujua", "root", "");
            script = koneksi.createStatement( );
}
        catch(SQLException ex){
            System.err.print(ex);
}
        catch(ClassNotFoundException ex){
            System.err.print(ex);
}
}
    public void tampilPetani(){
        try{
             int baris = tbl_DAPetani.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakPetani.delete(0, baris);
        }

String sql = "select * from akunPetani";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
Petani kontak = new Petani( );
kontak.setNama(rs.getString(1));
kontak.setAlamat(rs.getString(2));
kontak.setNomorTelephone(rs.getInt(3));
kontak.setUsername(rs.getString(4));
kontak.setPassword(rs.getString(5));

    DataKontakPetani.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
    public void tampilPetugas(){
        try{
             int baris = tbl_DAPetugas.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakPetugas.delete(0, baris);
        }

String sql = "select * from akunPetugas";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
Petugas kontak = new Petugas( );
kontak.setNama(rs.getString(1));
kontak.setAlamat(rs.getString(2));
kontak.setNomorTelephone(rs.getInt(3));
kontak.setUsername(rs.getString(4));
kontak.setPassword(rs.getString(5));

    DataKontakPetugas.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
      public void tampilLaporan(){
        try{
             int baris = tbl_Laporan.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakPetugas.delete(0, baris);
        }

String sql = "select * from laporan";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
Laporan kontak = new Laporan();
kontak.setNamaPetugas(rs.getString(1));
kontak.setTanggalPublish(rs.getInt(2));
kontak.setSubjek(rs.getString(3));
kontak.setLaporan(rs.getString(4));

    DataKontakLaporan.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
       public void tampilDHT(){
        try{
             int baris = tblDHT.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakDHT.delete(0, baris);
        }

String sql = "select * from datahasiltani ";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
hasilTani kontak = new hasilTani();
kontak.setKecamatan(rs.getString(1));
kontak.setJenisTani(rs.getString(2));
kontak.setBulan(rs.getString(2));   
kontak.setJumlah(rs.getInt(3));

    DataKontakDHT.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
      public void tampilBalige(){
        try{
             int baris = tblBalige.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakHTBalige.delete(0, baris);
        }

String sql = "select * from datahasiltani where Kecamatan = 'Balige' ";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
hasilTani kontak = new hasilTani();
//kontak.setKecamatan(rs.getString(1));
kontak.setJenisTani(rs.getString(2));
kontak.setBulan(rs.getString(4));
kontak.setJumlah(rs.getInt(3));

    DataKontakHTBalige.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
      public void tampilSigumpar(){
        try{
             int baris = tblSigumpar.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakHTSigumpar.delete(0, baris);
        }

String sql = "select * from datahasiltani where Kecamatan = 'Sigumpar' ";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
hasilTani kontak = new hasilTani();
//kontak.setKecamatan(rs.getString(1));
kontak.setJenisTani(rs.getString(2));
kontak.setBulan(rs.getString(4));
kontak.setJumlah(rs.getInt(3));

    DataKontakHTSigumpar.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
      public void tampilLaguboti(){
        try{
             int baris = tblLaguboti.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakHTLaguboti.delete(0, baris);
        }

String sql = "select * from datahasiltani where Kecamatan = 'Laguboti' ";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
hasilTani kontak = new hasilTani();
//kontak.setKecamatan(rs.getString(1));
kontak.setJenisTani(rs.getString(2));
kontak.setBulan(rs.getString(4));
kontak.setJumlah(rs.getInt(3));

    DataKontakHTLaguboti.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
      public void tampilPorsea(){
        try{
             int baris = tblPorsea.getRowCount();
                for(int i=0; i<baris; i++){
                DataKontakHTPorsea.delete(0, baris);
        }

String sql = "select * from datahasiltani where Kecamatan = 'Porsea' ";
ResultSet rs = script.executeQuery(sql);

while (rs.next()){
hasilTani kontak = new hasilTani();
//kontak.setKecamatan(rs.getString(1));
kontak.setJenisTani(rs.getString(2));
kontak.setBulan(rs.getString(4));
kontak.setJumlah(rs.getInt(3));

    DataKontakHTPorsea.add(kontak);
}
}
        catch(SQLException ex){
            System.err.print(ex);
            
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasiStatistikTaniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasiStatistikTaniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasiStatistikTaniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasiStatistikTaniAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasiStatistikTaniAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FEApasswordBaru;
    private javax.swing.JTextField FEApasswordLama;
    private javax.swing.JRadioButton FEApetani;
    private javax.swing.JRadioButton FEApetugas;
    private javax.swing.JTextField FEAusernameBaru;
    private javax.swing.JTextField FEAusernameLama;
    private javax.swing.JTextField FPAalamat;
    private javax.swing.JTextField FPAnama;
    private javax.swing.JTextField FPAnomorTelephone;
    private javax.swing.JTextField FPApassword;
    private javax.swing.JRadioButton FPApetani;
    private javax.swing.JRadioButton FPApetugas;
    private javax.swing.JButton FPAtambahAkun;
    private javax.swing.JTextField FPAusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tblBalige;
    private javax.swing.JTable tblDHT;
    private javax.swing.JTable tblLaguboti;
    private javax.swing.JTable tblPorsea;
    private javax.swing.JTable tblSigumpar;
    private javax.swing.JTable tbl_DAPetani;
    private javax.swing.JTable tbl_DAPetugas;
    private javax.swing.JTable tbl_Laporan;
    // End of variables declaration//GEN-END:variables
}
